local keymap = vim.keymap

keymap.set("n", "<F1>", "<cmd>echo<cr>")
keymap.set("i", "<F1>", "<esc><cmd>echo<cr>")
keymap.set("n", "<c-a>", "ggvG$")
keymap.set("i", "jk", "<esc>")
keymap.set("i", "kj", "<esc>")
keymap.set("t", "<<", "<c-\\><c-n>")
keymap.set("t", "<c-l>", "<right>")
keymap.set("t", "<c-j>", "<c-\\><c-n><c-w>j")
keymap.set("t", "<c-k>", "<c-\\><c-n><c-w>k")
keymap.set("t", "<c-h>", "<c-\\><c-n><c-w>h")
keymap.set("i", "<c-l>", "<esc><c-w>l")
keymap.set("i", "<c-j>", "<esc><c-w>j")
keymap.set("i", "<c-k>", "<esc><c-w>k")
keymap.set("i", "<c-h>", "<esc><c-w>h")
keymap.set("n", "<c-l>", "<c-w>l")
keymap.set("n", "<c-j>", "<c-w>j")
keymap.set("n", "<c-k>", "<c-w>k")
keymap.set("n", "<c-h>", "<c-w>h")
